language: node_js
node_js:
- 8.3.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script: npm test
before_deploy:
- npm run build
env:
  global:
  # AWS_ACCESS_KEY
  - secure: RK20JbXy892ZIINsaDz45Q2nIDRGFAg2MYARWvdJP8/AFFjq98aRxFcWZ6gg+6Xbf8sIvvm/bCMrXQaf9b0pIjRnnP/F+tledkt4bm8jQrYrVJkjiC/TxBX1Nml+dOxrEnDmtTSnSy4U6KnEqvacpFqBkZwlwm1HGmCgeYl5xCyJuANYjjmCwsERL5vH4xeJbm0mphHm/J7p7vXlBgl3MHz2Q6F6hEq3YI9lDqcY4w+OiO0cyEzmW0NqpYSLMO7F/CKD7ncJy3BRqPyGAcnfY/b4zA9iGpjXQ3Mx8alzgHLU2DomhELrPuSmt07LOP/DRLL2ZX49dwJ/odlYKG/otFk046JzS3lgX2amWyBPLSVz69zTfh0vKMNyxkC46pHWSlIAK4SaI6ZQeyHvN1W6AqfKO5Sp81NdX+LffnXau739xjBJ/7/wHDm2oUn6HtoJ6qcPK1msxuvm/aF5cRaLnbmOKw5cZqcZkVucjPvQRLS/RFh6rFit9t3dw9U3zcLloP0DsWvQzQ6A2zwKRHgoLf0Kf82FvQH5Ell/KMWrHex7dJQEzWLs2BnnnBGWjqc0/HLDHFHeGvYU3bZWAqj2Q4NtHP4wAQgYBqa2R1eYE+qS0u7rFk4X4cFlvPyM5U/uprwBovWU9YGfhqgleGGhO9uAud9DGm1EO2w2n5DmpZQ=
  # AWS_SECRET_ACCESS_KEY
  - secure: S1EFJ5CMd9vlBXTkxYxgJ/YHgMDuMxtHFC+trRVTOJg+d9OdBtZAskz0bihAQ1cKy7K2WNy6NPS74Ke/a/f/krIXBFZEY23goEPQzM7afgrzwObT9Kf4HVt4VbFRHCLve833c1aEvmHtBVw0Kiwlg9fcDHXdRlcAQ0pKHNEOOOycgsF81vD0D7F//9iZPc/NWAeCj3pCd/pzEFXN8T0yML2h17g9nO49082Vu3uari7V44GejPaVK8xHvlIuGCjRmsxGWgrihBy2dGitZLEsnJ3FbbVYSj+UPglWCKuQbAOeGNqvisqHo6MNw30XNY20DfnrGPISN3VShVav6dHZeHNVux7tk/L+FLow/GFLFwKk2XenHP7YSQswY2LmgnyzR0WU0KfHgsHs3GWv2HXyccpzjqSKtarYxrF+gKIhTNTv5f36yC/rJIaI07whGTiOdD0nCM1CDNGEUb6epo0P0Aiv/0Gd+SpA1L53pxiwi+7uW5E5Ix5Y8xiTFaJMLyjOInvEKeEy6qCaYQXTMQabJ4NTIqwS18u7PCV1+lm7HO8gF6Kk8dd5Bu0BUzNVF/Mqdhe8q2vU7S/EzxjJEIHQLBm7BbFvuPWw1Hq6eWBTxAqG30kzKDAyAQgW4ltsQzzGWSMlar3+6hyh/efg8WSZc1DSfw2GziXWux8Qhlz5ipk=
  # REACT_APP_API_URL
  - secure: nPyPnoMerJMEttNQwNo608G+4Sj9ialHDRInFyjGEKsNBrmpAZGRYLzaiW5k15dT6SHzlnEWZiwYt0sF1FUUUjKzZAVmAycwvzhb0ySjXilQReHtSxcyOGDa+6ltAKa94RF+Xin9eRwNU018BQ/sXO86LU5DlI/Qou2Zvvkev44rJzBWfEyeeM5xo3baTK6EOluHwljyJJMx9Eh/XqnrrAXDmHU/DLQ4m0sNZ9/XnJ9Ff8/XArwWDnOQ3fe0Ks0gvh/mlonbQnTkTuQmFxQjOyEdDKQWUb23z56iKFtqWYrFp2GD8azFlFj57DkMCljJn7KYrI/y5WyaX0u2fbPabws7zqi+U2xTB1lMMe6NCQ7lhInMPB3gc4nviMQOrLcaG9NfIDcizppIzRAe7PvlIYTd1wKxjQs9RMUIiPTh/akq0nk+QovLjgCf3zzAefmIF5u6BknFYGk9PUXJBeJl1o4yclfvIT94fWwV6Pqfp/Rv6DXAFLMwphZHmTEvJIadpLQGkRj2xcC1Eg3UixlrvZD//JHxNSHtoWUaDjZkicrpDkVrBVo/Yk/xV78HFco840a25VoAZv/BO7N2HM4I8lqikI/xLMdlDzBR0MJF5OnKeYVMTGgayp4rtgu9T6Y5trjGcwLIq5Z9Dmv7OfjZqnrMThsvdyn1r7z9Zvc5p7Y=
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: quarters-admin-staging
  local-dir: build
  skip_cleanup: true
  acl: public_read
  on:
    repo: quartersapp/quarters-admin
    branch: master
