language: node_js
node_js:
- 8.3.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
script: npm test -- --coverage --ci --runInBand
before_deploy:
- npm run build
env:
  global:
  # AWS_ACCESS_KEY
  - secure: BNJAm205iG2xTHIKuTysWUtNw9Hv32tJrxqmKgwCKsHKzRchdfJWWtZSuePg7gSpyx3Zh7ruGQxmDQZ/IYC5xylCkzaIpSEJ1naGxm4dkXnJuBvcVd2gu/zjKgV3CY0zAkDW+s5sqLO0P/fXnVBBNW3Zp9Dy05uAahWyB5b8BucwAs9eu9HkptZeSqF/Vimdz7wQpMU0u08JOAXIjrpgmuM3KzzZ10lrBJ/Ydum+KeHYGBCbs5jy3Ehwkp1BVPTMQN5sSX7+MkM1TVzrUsA9KVVJA/ca06+EE+9cc2r/ewSaJJvzKtqcbYtHsCVRJqBZ/BxXxjbFAF/9LOkjyAohrxCig+LCcfLh/YukSST+MKgS7MFh9CkUDEI1pVXQZVUjnt1mSK3DQP+aVBraSGCvLuICbTLUMseOmoFuFUDwtWfPMkLmZWyClahVTAEuBZBREDj4VHNsXKgLOj1CDogYOvSgtc9SdmqQVWGbdA2Ied+me37rGe4gvIqUsEeY1hBb51Vs11BoL6cG+P8eQV/wFBxlJWTRPeDGx6y5idAs3rqZJUDJwilUSfBjM3j7+rR12odeGkVAcg5Nba+md1blfPbs4pVjLsnOaAzKZArrEylj22OXvvQh2CBL7shVWT6Kj608QbmRfX9U+kreVm+oEw3PiOECiRqiJCRO8TUMKnA=
  # AWS_SECRET_ACCESS_KEY
  - secure: OLhoc+K+c8vUYYUCpIwUpflRPY+H2uT3n7xRGQaiZzLDMOKg8hbK4CUvyRzPIdW8SHl4BIdsXQJsxMrbqzZBu8m+s1MUnsOLGzCtQXBLTscURIQVNEuXc7dgf0Htsl/1gbZzF70BDglOvK+EDddayMUuKQd5aDtLuQM5Zja5PX4vBSZWRqg3cyJjK2ZdtO6psdTEEGyRYMavoR+u8EXqWW31BRDGNm5b3h9rSWnEHiCgvyiGVIIBCJxHaj26MaaUAugFAEQpPQyRXJC26TENpjVYdeMNPyBFJuXUkA4sPMewJj5TIG+5x8LPV+4kgrptYfI7jtFQByGkyK6uv5UQzhi05Zsrd6G+8Tgeo9dhhI1DAAKR/hj3FwHBusYnSpDHX3k/azv/DuDlR8UqCjSsIn8bdbYjJ8mRX1sqe2caSOev5lGAVc931+dIFLmsD3uKFBcoKNLnxSP9mRertYwOGP5KDWZRyV+bm3BI8qPqYIz+qiBtHofG72IjoWZ0wwVDa0RyjtBUBP4pN6Q7/j0XQVQL/TFLaQrQjRs8sJYd2lNCVOvAYazC19pzcqPaaxkbpM8X2+Iud8JLRPPYYOqTKsO29sL/vSzvq1ukxKjaGRyWcmWokcjtLsD8jWo8Yrcz1vI0a+XOD/UlCzIfeTjB6PosDX4Slp6Li8u7R28GAO0=
  # REACT_APP_API_URL
  - secure: nPyPnoMerJMEttNQwNo608G+4Sj9ialHDRInFyjGEKsNBrmpAZGRYLzaiW5k15dT6SHzlnEWZiwYt0sF1FUUUjKzZAVmAycwvzhb0ySjXilQReHtSxcyOGDa+6ltAKa94RF+Xin9eRwNU018BQ/sXO86LU5DlI/Qou2Zvvkev44rJzBWfEyeeM5xo3baTK6EOluHwljyJJMx9Eh/XqnrrAXDmHU/DLQ4m0sNZ9/XnJ9Ff8/XArwWDnOQ3fe0Ks0gvh/mlonbQnTkTuQmFxQjOyEdDKQWUb23z56iKFtqWYrFp2GD8azFlFj57DkMCljJn7KYrI/y5WyaX0u2fbPabws7zqi+U2xTB1lMMe6NCQ7lhInMPB3gc4nviMQOrLcaG9NfIDcizppIzRAe7PvlIYTd1wKxjQs9RMUIiPTh/akq0nk+QovLjgCf3zzAefmIF5u6BknFYGk9PUXJBeJl1o4yclfvIT94fWwV6Pqfp/Rv6DXAFLMwphZHmTEvJIadpLQGkRj2xcC1Eg3UixlrvZD//JHxNSHtoWUaDjZkicrpDkVrBVo/Yk/xV78HFco840a25VoAZv/BO7N2HM4I8lqikI/xLMdlDzBR0MJF5OnKeYVMTGgayp4rtgu9T6Y5trjGcwLIq5Z9Dmv7OfjZqnrMThsvdyn1r7z9Zvc5p7Y=
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: quarters-admin-staging
  local-dir: build
  skip_cleanup: true
  acl: public_read
  on:
    repo: quartersapp/quarters-admin
    branch: master
